version: '3.8'
services:
  bot:
    build: .
    volumes:
      - ./:/app
      - bot_data:/app/database
      - ./fonts:/app/fonts
      - ./icons:/app/icons
    ports:
      - "5001:5001"
    environment:
      - BOT_ENV=production
      - DISCORD_TOKEN=DISCORD_TOKEN
      - ADMIN_IDS=ADMIN_IDS
      - CLIENT_ID=CLIENT_ID
      - CLIENT_SECRET=CLIENT_SECRET
      - REDIRECT_URI=REDIRECT_URI
    restart: unless-stopped
    container_name: discord-wrapped-bot

volumes:
  bot_data:
    name: discord_wrapped_data